@EnergymApi_HostAddress = http://localhost:5070

### Requisição GET para listar todos os usuários
GET {{EnergymApi_HostAddress}}/usuarios
Accept: application/json

### Requisição GET para listar todas as academias
GET {{EnergymApi_HostAddress}}/academias
Accept: application/json

### Requisição GET para listar todos os endereços
GET {{EnergymApi_HostAddress}}/enderecos
Accept: application/json

### Requisição GET para listar todos os registros de exercícios
GET {{EnergymApi_HostAddress}}/registrosexercicios
Accept: application/json

### Requisição GET para listar todos os prêmios
GET {{EnergymApi_HostAddress}}/premios
Accept: application/json

### Requisição GET para listar todos os resgates
GET {{EnergymApi_HostAddress}}/resgates
Accept: application/json

###
